name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy_portfolio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_7BD98 }}'
          projectId: portfolio-7bd98
          channelId: live
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
